// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/your-content": {
    params: {};
  };
  "/quiz": {
    params: {};
  };
  "/quiz/results": {
    params: {};
  };
  "/technology-types": {
    params: {};
  };
  "/activities": {
    params: {};
  };
  "/activity-sets": {
    params: {};
  };
  "/alternative-social-tech": {
    params: {};
  };
  "/contributors": {
    params: {};
  };
  "/content/:pageId": {
    params: {
      "pageId": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/your-content" | "/quiz" | "/quiz/results" | "/technology-types" | "/activities" | "/activity-sets" | "/alternative-social-tech" | "/contributors" | "/content/:pageId" | "/*";
  };
  "features/home/HomePage.jsx": {
    id: "features/home/HomePage";
    page: "/";
  };
  "components/YourContentPage.jsx": {
    id: "components/YourContentPage";
    page: "/your-content";
  };
  "features/quiz/Quiz.jsx": {
    id: "features/quiz/Quiz";
    page: "/quiz";
  };
  "features/quiz/Results.jsx": {
    id: "features/quiz/Results";
    page: "/quiz/results";
  };
  "features/quiz/TechnologyTypesPage.jsx": {
    id: "features/quiz/TechnologyTypesPage";
    page: "/technology-types";
  };
  "components/ActivitiesPage.jsx": {
    id: "components/ActivitiesPage";
    page: "/activities";
  };
  "components/ActivitySetsPage.jsx": {
    id: "components/ActivitySetsPage";
    page: "/activity-sets";
  };
  "components/AlternativeSocialTechPage.jsx": {
    id: "components/AlternativeSocialTechPage";
    page: "/alternative-social-tech";
  };
  "components/ContributorsPage.jsx": {
    id: "components/ContributorsPage";
    page: "/contributors";
  };
  "routes/ContentPage.jsx": {
    id: "routes/ContentPage";
    page: "/content/:pageId";
  };
  "routes/NotFoundPage.jsx": {
    id: "routes/NotFoundPage";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "features/home/HomePage": typeof import("./app/features/home/HomePage.jsx");
  "components/YourContentPage": typeof import("./app/components/YourContentPage.jsx");
  "features/quiz/Quiz": typeof import("./app/features/quiz/Quiz.jsx");
  "features/quiz/Results": typeof import("./app/features/quiz/Results.jsx");
  "features/quiz/TechnologyTypesPage": typeof import("./app/features/quiz/TechnologyTypesPage.jsx");
  "components/ActivitiesPage": typeof import("./app/components/ActivitiesPage.jsx");
  "components/ActivitySetsPage": typeof import("./app/components/ActivitySetsPage.jsx");
  "components/AlternativeSocialTechPage": typeof import("./app/components/AlternativeSocialTechPage.jsx");
  "components/ContributorsPage": typeof import("./app/components/ContributorsPage.jsx");
  "routes/ContentPage": typeof import("./app/routes/ContentPage.jsx");
  "routes/NotFoundPage": typeof import("./app/routes/NotFoundPage.jsx");
};