name: Deploy to GitHub Pages
on:
  push:
    branches: ['main']
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm run build
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v4
        with:
          path: './build/client'
      - uses: actions/deploy-pages@v5
